" SETTINGS ---------------------------------------------------------------- {{{
" Add numbers to each line on the left-hand side.
set number
set relativenumber

" disable compatibility with vi which can cause unexpected issues.
set nocompatible
"Enable type file detection. Vim will be able to try to detect the type offile in use.
filetype on
" Enable plugins and load plugin for the detected file type.
filetype plugin on
" Load an indent file for the detected file type.
filetype indent on
" Turn syntax highlighting on.
syntax on
" Highlight cursor line underneath the cursor horizontally
set cursorline

" Set shift width to 4 spaces.
set shiftwidth=4
" Set tab width to 4 columns.
set tabstop=4
" Use space characters instead of tabs.
set expandtab
" Do not save backup files.
set nobackup

" Do not let cursor scroll below or above N number of lines when scrolling.
set scrolloff=10
" Do not wrap lines. Allow long lines to extend as far as the line goes.
set nowrap
" While searching though a file incrementally highlight matching characters as you type.
set incsearch
" Ignore capital letters during search.
set ignorecase
" Override the ignorecase option if searching for capital letters.
" This will allow you to search specifically for capital letters.
set smartcase

" Show partial command you type in the last line of the screen.
set showcmd
" Show the mode you are on the last line.
set showmode
" Show matching words during a search.
set showmatch
" Use highlighting when doing a search.
set hlsearch
" Set the commands to save in history default number is 20.
set history=1000

" Enable mouse mode
set mouse=a

" Enable 24-bit colour if available
if (has("termguicolors"))
  set termguicolors
endif

" Use a line cursor within insert mode and a block cursor everywhere else.
" Reference chart of values:
"   Ps = 0  -> blinking block.
"   Ps = 1  -> blinking block (default).
"   Ps = 2  -> steady block.
"   Ps = 3  -> blinking underline.
"   Ps = 4  -> steady underline.
"   Ps = 5  -> blinking bar (xterm).
"   Ps = 6  -> steady bar (xterm).
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"


" }}}

" PLUGINS ---------------------------------------------------------------- {{{
" Load plugins using Vim Plug plugin manager
" Run :PlugUpdate to install/update, and :PlugClean to remove unused plugins

call plug#begin()

" List your plugins here
Plug 'flazz/vim-colorschemes' " Install a bunch of color schemes

Plug 'sheerun/vim-polyglot' " lanjuage packs

Plug 'preservim/nerdtree'   " File tree, open with :NERDTree
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'ryanoasis/vim-devicons'

Plug 'yegappan/lsp' " lsp for inline errors and autocompletion

Plug 'liuchengxu/vim-which-key' " show shortcuts
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } } " fuzzy file finding
Plug 'tpope/vim-fugitive' " Git operations :Git
Plug 'airblade/vim-gitgutter' " Show git changes on left of the line numbers
Plug 'machakann/vim-highlightedyank'
Plug 'romainl/vim-cool' " Disable search highlighting after finished searching

Plug 'vim-airline/vim-airline' " statusline at bottom
Plug 'vim-airline/vim-airline-themes'

call plug#end()


set background=dark    " Setting dark mode
colorscheme molokai

" Start NERDTree and put the cursor back in the other window.
autocmd VimEnter * NERDTree | wincmd p
" Exit Vim if NERDTree is the only window remaining in the only tab.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | call feedkeys(":quit\<CR>:\<BS>") | endif

" For vim-devicons
set encoding=UTF-8

" For vim-airline
let g:airline_powerline_fonts = 1 " nerd fonts seem to work as well

" For WhichKey
nnoremap <silent> <leader> :WhichKey '<Space>'<CR>

" Clangd language server
let lspOpts = #{autoHighlightDiags: v:true}
autocmd User LspSetup call LspOptionsSet(lspOpts)

let lspServers = [#{
        \         name: 'clang',
        \         filetype: ['c', 'cpp'],
        \         path: expand('~/.vim/lsp/clangd_21.1.0/bin/clangd'),
        \         args: ['--background-index']
        \ }]
autocmd User LspSetup call LspAddServer(lspServers)

" }}}
